import { ScenarioDefinition, POI } from '../types';

export const SCENARIOS: ScenarioDefinition[] = [
  {
    id: 'intro',
    sceneNumber: 1,
    title: 'Kolkata 2050',
    subtitle: 'EXPERIENCE THE CITY OF TOMORROW',
    badge: 'CINEMATIC INTRO',
    description: 'A distant atmospheric twilight skyline over the Hooghly River. Welcome to the year 2050. Your journey begins now.',
    ambientLightColor: 0x446699,
    ambientIntensity: 1.5,
    sunColor: 0xffeedd,
    sunIntensity: 2.0,
    sunPosition: [80, 130, -100],
    fogColor: 0x16263e,
    fogDensity: 0.0012,
    weather: 'clear',
    rainActive: false,
    lightningActive: false,
    waterLevel: 0.0,
    heatHaze: false,
    airQualityStatus: 'Moderate (AQI 110)',
    playerPosition: [0, 8, 32],
    lookAtPosition: [0, 16, -60],
    keyTakeaway: 'The future of Kolkata stands at a historic crossroads between climate vulnerability and visionary resilience.'
  },
  {
    id: 'arrival',
    sceneNumber: 2,
    title: 'Arrival in 2050',
    subtitle: 'STREET LEVEL PERSPECTIVE',
    badge: 'IMMERSIVE STREETSCAPE',
    description: 'You stand at street level amidst colossal vertical biophilic towers, automated electric trams, and elevated sky-metro arteries.',
    ambientLightColor: 0x5577aa,
    ambientIntensity: 1.6,
    sunColor: 0xfff2e0,
    sunIntensity: 2.2,
    sunPosition: [120, 160, 90],
    fogColor: 0x182840,
    fogDensity: 0.001,
    weather: 'clear',
    rainActive: false,
    lightningActive: false,
    waterLevel: 0.0,
    heatHaze: false,
    airQualityStatus: 'Good (AQI 35)',
    playerPosition: [0, 2.0, 12],
    lookAtPosition: [0, 12, -45],
    keyTakeaway: 'Human scale within colossal architecture: pedestrian promenades are protected below layered transit arteries.'
  },
  {
    id: 'exploration',
    sceneNumber: 3,
    title: 'City Exploration',
    subtitle: 'POINTS OF INTEREST',
    badge: 'FREE ROAM',
    description: 'Walk or teleport freely across the futuristic boulevard, examining interactive holographic beacons and infrastructure nodes.',
    ambientLightColor: 0x6688bb,
    ambientIntensity: 1.6,
    sunColor: 0xffffff,
    sunIntensity: 2.2,
    sunPosition: [100, 170, 60],
    fogColor: 0x1a2b44,
    fogDensity: 0.001,
    weather: 'clear',
    rainActive: false,
    lightningActive: false,
    waterLevel: 0.0,
    heatHaze: false,
    airQualityStatus: 'Good (AQI 35)',
    playerPosition: [-5, 2.0, -10],
    lookAtPosition: [15, 8, -35],
    keyTakeaway: 'Select floating holographic icons with your controller ray to unlock STEM insights.'
  },
  {
    id: 'flooding',
    sceneNumber: 4,
    title: 'Extreme Rainfall',
    subtitle: 'CLIMATE RESILIENCE & FLOOD RESPONSE',
    badge: 'MONSOON 2050',
    description: 'Intense convective precipitation inundates the district. Watch automated storm barriers deploy and subterranean sponge vaults activate.',
    ambientLightColor: 0x334866,
    ambientIntensity: 1.2,
    sunColor: 0x5588bb,
    sunIntensity: 0.9,
    sunPosition: [20, 110, -40],
    fogColor: 0x142033,
    fogDensity: 0.0022,
    weather: 'storm',
    rainActive: true,
    lightningActive: true,
    waterLevel: 0.85,
    heatHaze: false,
    airQualityStatus: 'Good (AQI 35)',
    playerPosition: [-2, 2.0, -5],
    lookAtPosition: [10, 6, -30],
    keyTakeaway: 'Permeable graphene pavements and bioswales absorb 250mm/hr cloudbursts, preventing catastrophic inundation.'
  },
  {
    id: 'heat',
    sceneNumber: 5,
    title: 'Extreme Heatwave',
    subtitle: 'URBAN HEAT ISLAND vs BIOCLIMATIC CANOPY',
    badge: '44°C HEAT WAVE',
    description: 'A blistering 44°C summer afternoon. Contrast asphalt heat radiation with passive misting cooling totems and dense urban forest canopies.',
    ambientLightColor: 0x887755,
    ambientIntensity: 2.0,
    sunColor: 0xffd888,
    sunIntensity: 2.6,
    sunPosition: [40, 180, 20],
    fogColor: 0x483a2c,
    fogDensity: 0.0015,
    weather: 'heatwave',
    rainActive: false,
    lightningActive: false,
    waterLevel: 0.0,
    heatHaze: true,
    airQualityStatus: 'Moderate (AQI 110)',
    playerPosition: [14, 2.0, -15],
    lookAtPosition: [0, 6, -10],
    keyTakeaway: 'Urban micro-forests and photovoltaic shading structures lower ambient pedestrian temperatures by 8°C to 10°C.'
  },
  {
    id: 'traffic',
    sceneNumber: 6,
    title: 'Smart Mobility & Transit',
    subtitle: 'AUTONOMOUS MULTI-TIER TRANSIT',
    badge: 'DECONGESTION',
    description: 'Kolkata’s legendary tramway evolved into silent magnetic-levitation surface pods, coordinated seamlessly with elevated sky-metro trains.',
    ambientLightColor: 0x5577aa,
    ambientIntensity: 1.6,
    sunColor: 0xeef6ff,
    sunIntensity: 2.2,
    sunPosition: [-80, 150, 50],
    fogColor: 0x182840,
    fogDensity: 0.001,
    weather: 'clear',
    rainActive: false,
    lightningActive: false,
    waterLevel: 0.0,
    heatHaze: false,
    airQualityStatus: 'Good (AQI 35)',
    playerPosition: [4, 2.0, 2],
    lookAtPosition: [-10, 10, -25],
    keyTakeaway: 'Zero private internal-combustion vehicles: 100% electrified autonomous grid yields 85% reduction in transit emissions.'
  },
  {
    id: 'air_quality',
    sceneNumber: 7,
    title: 'Air Quality Dynamics',
    subtitle: 'SMOG RISK vs PURIFIED CORRIDORS',
    badge: 'AQI VISUALIZATION',
    description: 'Inspect particulate matter filtration towers and green lung corridors combating particulate winter inversions in the Gangetic basin.',
    ambientLightColor: 0x666650,
    ambientIntensity: 1.4,
    sunColor: 0xf0d890,
    sunIntensity: 1.8,
    sunPosition: [60, 120, -80],
    fogColor: 0x363228,
    fogDensity: 0.002,
    weather: 'smog',
    rainActive: false,
    lightningActive: false,
    waterLevel: 0.0,
    heatHaze: false,
    airQualityStatus: 'Severe (AQI 340)',
    playerPosition: [-8, 2.0, -18],
    lookAtPosition: [5, 14, -40],
    keyTakeaway: 'Smog-eating photocatalytic facade coatings and ionic bio-filters reduce PM2.5 levels from dangerous 340 to safe 35.'
  },
  {
    id: 'green',
    sceneNumber: 8,
    title: 'Green Kolkata District',
    subtitle: 'VERTICAL BIODIVERSITY & URBAN FORESTRY',
    badge: 'ECOLOGICAL HABITAT',
    description: 'Step into Kolkata’s regenerated green heart: vertical gardens climbing 40-storey facades, native bird sanctuaries, and riverfront mangroves.',
    ambientLightColor: 0x337744,
    ambientIntensity: 1.7,
    sunColor: 0xddffdd,
    sunIntensity: 2.2,
    sunPosition: [90, 160, 70],
    fogColor: 0x163020,
    fogDensity: 0.001,
    weather: 'clear',
    rainActive: false,
    lightningActive: false,
    waterLevel: 0.0,
    heatHaze: false,
    airQualityStatus: 'Good (AQI 35)',
    playerPosition: [18, 2.0, -22],
    lookAtPosition: [0, 12, -10],
    keyTakeaway: 'Integrating East Kolkata Wetland bioremediation principles into vertical architecture filters 60% of urban greywater naturally.'
  },
  {
    id: 'energy',
    sceneNumber: 9,
    title: 'Smart Clean Energy Grid',
    subtitle: 'SOLAR, WIND & FLOW STORAGE',
    badge: 'ZERO CARBON',
    description: 'Observe real-time animated energy flows: rooftop perovskite solar arrays and aerodynamic vertical-axis wind turbines powering the smart grid.',
    ambientLightColor: 0x335588,
    ambientIntensity: 1.5,
    sunColor: 0x88ddff,
    sunIntensity: 2.0,
    sunPosition: [-50, 140, -100],
    fogColor: 0x14243b,
    fogDensity: 0.0012,
    weather: 'clear',
    rainActive: false,
    lightningActive: false,
    waterLevel: 0.0,
    heatHaze: false,
    airQualityStatus: 'Good (AQI 35)',
    playerPosition: [-15, 2.0, -25],
    lookAtPosition: [10, 18, -45],
    keyTakeaway: 'Decentralized microgrids with solid-state iron-flow batteries ensure 100% resilient power during severe cyclonic disturbances.'
  },
  {
    id: 'night',
    sceneNumber: 10,
    title: 'Kolkata 2050 at Night',
    subtitle: 'CYBER-HERITAGE ILLUMINATION',
    badge: 'NIGHT SPECTACLE',
    description: 'A breathtaking nocturnal panorama: Howrah Bridge 2.0 illuminated in reactive cyan and gold, floating holographic Bengali signs, and vibrant river reflections.',
    ambientLightColor: 0x243355,
    ambientIntensity: 1.1,
    sunColor: 0x4466aa,
    sunIntensity: 0.8,
    sunPosition: [0, -50, -100],
    fogColor: 0x0c1424,
    fogDensity: 0.0016,
    weather: 'night',
    rainActive: false,
    lightningActive: false,
    waterLevel: 0.0,
    heatHaze: false,
    airQualityStatus: 'Good (AQI 35)',
    playerPosition: [0, 4.0, 15],
    lookAtPosition: [0, 20, -50],
    keyTakeaway: 'Smart adaptive LED streetscapes and bioluminescent plants provide glare-free nocturnal lighting while preserving dark-sky bird migration.'
  },
  {
    id: 'vision',
    sceneNumber: 11,
    title: 'Future Vision: 2050 & Beyond',
    subtitle: 'THE FUTURE IS SOMETHING WE DESIGN',
    badge: 'OBSERVATION SKY-DECK',
    description: 'High above the futuristic metropolis on an expansive observation sky-deck. A panoramic horizon of Kolkata resiliently thriving in 2050.',
    ambientLightColor: 0x334a66,
    ambientIntensity: 1.4,
    sunColor: 0xffaa66,
    sunIntensity: 1.8,
    sunPosition: [160, 65, -140],
    fogColor: 0x161e2e,
    fogDensity: 0.001,
    weather: 'sunset',
    rainActive: false,
    lightningActive: false,
    waterLevel: 0.0,
    heatHaze: false,
    airQualityStatus: 'Good (AQI 35)',
    playerPosition: [0, 78, -15],
    lookAtPosition: [0, 40, -120],
    keyTakeaway: '“The future is not a destination. The future is something we design.”'
  }
];

export const POINTS_OF_INTEREST: POI[] = [
  {
    id: 'howrah_2050',
    name: 'Howrah Bridge 2050',
    bengaliName: 'হাওড়া সেতু ২.০',
    category: 'landmark',
    position: [0, 24, -135],
    description: 'The iconic 1943 cantilever redesigned with carbon-nanotube reinforced steel, kinetic energy capture dampers, and two-tier magnetic transit.',
    didYouKnow: 'The bridge structure naturally generates 1.2 megawatts from tidal currents and acoustic wind vibrations.'
  },
  {
    id: 'futuristic_metro',
    name: 'Elevated Sky-Metro 2050',
    bengaliName: 'উন্নত আকাশ-মেট্রো',
    category: 'mobility',
    position: [-22, 14, -30],
    description: 'High-speed evacuated vacuum-tube and magnetic levitation lines connecting Howrah, Esplanade, Salt Lake, and New Town in under 8 minutes.',
    didYouKnow: 'The metro network operates entirely on regenerative deceleration braking, returning 32% of kinetic energy back to the city grid.'
  },
  {
    id: 'smart_street',
    name: 'Biophilic Smart Boulevard',
    bengaliName: 'স্মার্ট সবুজ সরণি',
    category: 'climate',
    position: [0, 2.5, -5],
    description: 'Permeable recycled composite roadways with induction charging coils beneath, automatically powering autonomous public transport in motion.',
    didYouKnow: 'Underneath this street lies a 50,000 m³ storm surge holding vault based on sponge city technology.'
  },
  {
    id: 'hooghly_river',
    name: 'Hooghly Eco-Aqueduct',
    bengaliName: 'হুগলি পুনরুজ্জীবিত নদী',
    category: 'nature',
    position: [40, 2, -100],
    description: 'Restored river banks with floating bio-wetlands, robotic silt collectors, and electric solar catamarans replacing fossil fuel ferries.',
    didYouKnow: 'Dissolved oxygen levels have rebounded to 7.8 mg/L, allowing river dolphin populations to thrive once more.'
  },
  {
    id: 'green_district',
    name: 'Vertical Forest Towers',
    bengaliName: 'উল্লম্ব অরণ্য ভবন',
    category: 'nature',
    position: [28, 12, -45],
    description: 'Residential towers engineered with over 15,000 indigenous trees and shrubs, absorbing 120 tonnes of carbon dioxide each year.',
    didYouKnow: 'Living walls act as natural acoustic buffers, dampening urban noise levels by 18 decibels.'
  },
  {
    id: 'smart_energy_hub',
    name: 'Solar-Wind Microgrid Hub',
    bengaliName: 'স্মার্ট শক্তি কেন্দ্র',
    category: 'energy',
    position: [-35, 10, -60],
    description: 'Dual-axis vertical helical wind turbines combined with transparent photovoltaic glass generating localized zero-emission power.',
    didYouKnow: 'This district operates as an islandable microgrid that maintains 100% uptime even during Category 5 Bay of Bengal cyclones.'
  }
];
